import numpy as np
import pandas as pd

from src.loading.database import select


def create_lag_features(df:pd.DataFrame, cols: list[str], lags: list[int]) -> pd.DataFrame:
    """Create temporal lag features and 3-hour variations or rolling sums.

    For precipitation, calculates a 3-hour rolling cumulative sum. For other
    features, calculates the 3-hour difference from the previous shift.

    Args:
        df (pd.DataFrame): Weather DataFrame containing the specified feature columns.
        cols (list[str]): List of column names to generate lag features for.
        lags (list[int]): List of lag intervals (time steps) to create.

    Returns:
        pd.DataFrame: DataFrame enriched with lag and rolling/variation features.
    """
    for col in cols:
        for lag in lags:
            df[f"{col}_lag_{lag}"] = df[col].shift(lag)
        
        if col == "precipitation":
            df[f"cumulative_{col}_3h"] = df[col].rolling(3).sum()
        else: 
            df[f"{col}_variation_3h"] = df[col] - df[col].shift(3)
    
    return df

def drop_null_lags(df:pd.DataFrame) -> pd.DataFrame:
    """Drop rows containing null values generated by lag and rolling calculations.

    Args:
        df (pd.DataFrame): DataFrame with NaN values from lagged columns.

    Returns:
        pd.DataFrame: DataFrame with all NaN rows removed.
    """
    df = df.dropna()
    
    return df

def create_time_cyclical_features(df:pd.DataFrame) -> pd.DataFrame:
    """Generate cyclical trigonometric features from timestamps.

    Computes sine and cosine transformations for hour of day and day of year.

    Args:
        df (pd.DataFrame): DataFrame containing a datetime 'time' column.

    Returns:
        pd.DataFrame: DataFrame with added cyclical features ('hour_sin',
            'hour_cos', 'day_sin', 'day_cos').
    """
    df["hour_sin"] = np.sin(2 * np.pi * df["time"].dt.hour/24)
    df["hour_cos"] = np.cos(2 * np.pi * df["time"].dt.hour/24)
    
    df["day_sin"] = np.sin(2 * np.pi * df["time"].dt.dayofyear/365)
    df["day_cos"] = np.cos(2 * np.pi * df["time"].dt.dayofyear/365)    
    
    return df

def create_target(df:pd.DataFrame) -> pd.DataFrame:
    """Create binary classification target variable for rain in the next hour.

    Args:
        df (pd.DataFrame): DataFrame containing the 'precipitation' column.

    Returns:
        pd.DataFrame: DataFrame with the 'rain_next_hour' target column (1 if
            next hour precipitation >= 0.2 mm, else 0).
    """
    df["rain_next_hour"] = (df["precipitation"].shift(-1) >= 0.2).astype(int)
    
    return df

def run_feature_engineering(df:pd.DataFrame)-> pd.DataFrame:
    """Execute the complete feature engineering pipeline.

    Applies lag features, cyclical time encodings, target creation, and removes
    null rows.

    Args:
        df (pd.DataFrame): Cleaned raw weather DataFrame.

    Returns:
        pd.DataFrame: Fully feature-engineered DataFrame ready for training.
    """
    lag_features = ["temperature_2m", "relative_humidity_2m", "pressure_msl", "wind_speed_10m", "precipitation"]
    
    return (df.copy()
            .pipe(create_lag_features, cols=lag_features, lags=[1,2,3,6])
            .pipe(create_time_cyclical_features)
            .pipe(create_target)
            .pipe(drop_null_lags)
            )
    

df = select("SELECT * FROM WEATHER")

df = run_feature_engineering(df=df)
